options:
  image:
    type: string
    description: "The docker image to install. Required. Defaults to Dockerhub wordpress:php7.3"
    default: "wordpress:php7.3"
  db_host:
    type: string
    description: "MySQL database host"
  db_user:
    type: string
    description: "MySQL database user"
    default: "wordpress"
  db_password:
    type: string
    description: "MySQL database user's password"
    default: ""
  container_config:
    type: string
    description: >
      YAML formatted map of container config keys & values. These are
      generally accessed from inside the image as environment variables.
      Use to configure customized Wordpress images. This configuration
      gets logged; use container_secrets for secrets.
    default: ""
  container_secrets:
    type: string
    description: >
      YAML formatted map of secrets. Works just like container_config,
      except that values should not be logged.
    default: ""
