options:
  image:
    type: string
    description: "The docker image to install. Required. Defaults to Dockerhub wordpress:php7.3"
    default: "wordpress:php7.3"
  image_user:
    type: string
    description: "Username to use for the configured image registry, if required"
    default: ""
  image_pass:
    type: string
    description: "Password to use for the configured image registry, if required"
    default: ""
  ports:
    type: string
    description: >
       Ports to expose, space separated list in name:8000 format. Names are alphanumeric + hyphen.
       eg. "http:80 metrics:7127"
    default: "http:80"
  db_host:
    type: string
    description: "MySQL database host"
    default: ""
  db_name:
    type: string
    description: "MySQL database name"
    default: "wordpress"
  db_user:
    type: string
    description: "MySQL database user"
    default: "wordpress"
  db_password:
    type: string
    description: "MySQL database user's password"
    default: ""
  container_config:
    type: string
    description: >
      YAML formatted map of container config keys & values. These are
      generally accessed from inside the image as environment variables.
      Use to configure customized Wordpress images. This configuration
      gets logged; use container_secrets for secrets.
    default: ""
  container_secrets:
    type: string
    description: >
      YAML formatted map of secrets. Works just like container_config,
      except that values should not be logged.
    default: ""
  initial_settings:
      type: string
      description: >
        Optional, YAML formatted, wordpress configuration. It is used only
        during initial deployment. Changing it at later stage has no effect.
        If set to non empty string required keys are:

            user_name: admin_username
            admin_email: name@example.com

        Optionally you can also provide

            weblog_title: Blog title  # empty by default
            admin_password: <secret>  # autogenerated if not set
            blog_public: False        # by default blogs are public

        If admin_password is not provided it will be automatically generated
        and stored on the operator pod in the /root directory
      default: ""
  blog_hostname:
    type: string
    description: Blog hostname
    default: "myblog.example.com"
  wp_plugin_akismet_key:
    type: string
    description: Akismet key. If empty, akismet will not be automatically enabled
    default: ""
  wp_plugin_openid_team_map:
    type: string
    description: >
      OpenID teams to grant access levels to, in native format.

      If empty, OpenID will not be enabled.

      Example format:

        a:4:{i:1;O:8:"stdClass":4:{s:2:"id";i:1;s:4:"team";s:19:"site-sysadmins";s:4:"role";s:13:"administrator";s:6:"server";s:1:"0";}i:2;O:8:"stdClass":4:{s:2:"id";i:2;s:4:"team";s:25:"site-editors";s:4:"role";s:6:"editor";s:6:"server";s:1:"0";}i:3;O:8:"stdClass":4:{s:2:"id";i:3;s:4:"team";s:24:"site-admins";s:4:"role";s:13:"administrator";s:6:"server";s:1:"0";}i:4;O:8:"stdClass":4:{s:2:"id";i:4;s:4:"team";s:9:"bloggers";s:4:"role";s:6:"editor";s:6:"server";s:1:"0";}}
    default: ""
